"""
Orchestrator — investigation workflow controller.

Accepts a free-text user query, runs the LLM planner, validates the plan,
resolves entities, executes agents step-by-step, enforces stop conditions,
and returns a fully structured OrchestratorResult.

The orchestrator is NOT an agent. It is a controller:
  - It does not produce summaries itself.
  - It does not call Neo4j directly.
  - It delegates planning to InvestigationPlanner, tool calls to MCPToolClient,
    and domain work to GraphAgent / RiskAgent / TraceAgent.

Execution flow
--------------
  1. Plan      — call InvestigationPlanner.plan(query) → PlannerResult
  2. Trace     — create and persist InvestigationTrace before any agent runs
  3. Validate  — call validate_plan MCP tool for all MCP-registered steps
  4. Resolve   — call resolve_entity MCP tool for each Company-type entity
  5. Execute   — run each plan step through the appropriate agent
                   inject canonical names; gate entity-dependent steps on resolution
  6. StopCheck — after each risk step, call evaluate_stop_conditions if plan
                   carries stop_conditions; halt remaining steps if triggered
  7. Finalize  — write final summary to trace; return OrchestratorResult

Entity gating
-------------
If resolve_entity returns no match for the primary entity, all plan steps are
skipped immediately and no agents are called. The final answer is generated by
the AI client (if configured) to explain the failure to the analyst.

Trace mode
----------
Trace queries skip entity resolution entirely. trace-agent steps run unconditionally.
"""

from __future__ import annotations

import difflib as _difflib
import json as _json
import logging
import queue as _queue_mod
import uuid
from dataclasses import dataclass, field
from typing import Any

from src.agents.graph_agent import GraphAgent
from src.agents.risk_agent import RiskAgent
from src.agents.trace_agent import TraceAgent
from src.clients.ai_client import AIClient
from src.clients.mcp_tool_client import MCPToolClient
from src.domain.models import AgentResult, EventType, InvestigationTrace, TraceEvent
from src.orchestration.planner import InvestigationPlanner, PlannerResult, PlanStep
from src.storage.trace_repository import TraceRepository
from src.tracing.trace_service import TraceService

_log = logging.getLogger(__name__)

_AGENT_DISPLAY: dict[str, str] = {
    "graph-agent":  "Graph Agent",
    "risk-agent":   "Risk Agent",
    "trace-agent":  "Trace Agent",
}

_FAILURE_SYSTEM_PROMPT = (
    "You are a UK financial crime compliance assistant. "
    "A structured investigation could not be completed. "
    "In 2-3 sentences, explain what went wrong and what the analyst should do next. "
    "Be concise and factual. Do not use bullet points or markdown."
)

_RISK_NARRATIVE_PROMPT = """You are a financial crime compliance analyst. \
Given structured risk signals for a company, write a concise risk assessment \
(2-4 sentences) for a compliance analyst deciding whether to escalate. \
Reference the specific signals provided. State the overall risk level (LOW / MEDIUM / HIGH). \
Do not use bullet points or markdown.

── SCORING REFERENCE ────────────────────────────────────────────────────────

Use the heuristics below to verify and contextualise the risk levels supplied
in the signals. Do not recalculate them — they are already computed. Use this
reference to ground your language and ensure your narrative is consistent with
the underlying logic.

OWNERSHIP COMPLEXITY
Inputs: max_depth (longest ownership chain in hops), unique_owners (distinct
owner nodes), corporate_only (True when no individual beneficial owners appear
anywhere in the chain).

Scoring:
  max_depth >= 4 hops      → +2 points
  max_depth 2 or 3 hops    → +1 point
  max_depth <= 1 hop        → +0 points (may also return UNKNOWN if no data)
  unique_owners >= 5        → +2 points
  unique_owners 2, 3, or 4 → +1 point
  unique_owners <= 1        → +0 points
  corporate_only = True     → +2 points (no natural-person UBO identified)

Risk level: score >= 4 → HIGH | score 2 or 3 → MEDIUM | score < 2 → LOW
Special case: if max_depth == 0 (no ownership data found) → UNKNOWN

Compliance interpretation:
  HIGH ownership complexity may indicate layered corporate structures used to
  obscure beneficial ownership — a common typology in money-laundering schemes
  and sanctions evasion. A corporate-only chain with no natural-person UBO is
  particularly significant: it may mean the ultimate beneficial owner has not
  been disclosed, which is a requirement under UK PSC rules.

CONTROL SIGNALS
Inputs: elevated (set of non-standard control types detected), mixed (True
when both share-based and non-share-based controls appear), has_data (False
when no ownership/control records exist).

Elevated control types that trigger HIGH risk:
  right-to-appoint-and-remove-directors
  right-to-appoint-and-remove-majority-of-directors
  significant-influence-or-control
  significant-influence-or-control-as-a-member-of-a-firm
  right-to-appoint-and-remove-members

Standard (non-elevated) control types:
  ownership-of-shares-25-to-50-percent
  ownership-of-shares-50-to-75-percent
  ownership-of-shares-75-to-100-percent
  voting-rights-25-to-50-percent
  voting-rights-50-to-75-percent
  voting-rights-75-to-100-percent

Risk level:
  elevated set is non-empty → HIGH (regardless of share ownership)
  mixed controls present     → MEDIUM (elevated absent but non-share types found)
  share/voting only          → LOW
  has_data = False           → UNKNOWN

Compliance interpretation:
  Elevated controls (especially significant-influence-or-control and
  right-to-appoint) are the hallmarks of shadow director arrangements and
  undisclosed controllers — common in corporate abuse typologies. Mixed
  controls warrant scrutiny because they may signal that formal share
  ownership is being supplemented with informal influence mechanisms.

ADDRESS RISK
Inputs: total (number of companies registered at the same address),
dissolution_rate (proportion of co-located companies that are dissolved),
threshold (default = 5, the minimum count before flagging).

Scoring:
  total >= threshold * 10   → +2 points  (mass co-location)
  total >= threshold         → +1 point
  total == 0                 → score stays 0, return LOW immediately
  dissolution_rate >= 0.50   → +2 points  (majority dissolved)
  dissolution_rate >= 0.25   → +1 point

Risk level: score >= 3 → HIGH | score >= 1 → MEDIUM | score == 0 → LOW

Compliance interpretation:
  Mass co-location at a single registered address (often a formation agent or
  virtual office) combined with a high dissolution rate is a well-documented
  shell-company indicator. The Companies House UBO data regularly shows
  hundreds of companies sharing a single address; when most of those companies
  are dissolved, it suggests systematic exploitation of registered address
  services for short-lived entities.

INDUSTRY CONTEXT
Inputs: is_holding (True when any of the company's SIC codes appears in the
high-scrutiny set), dissolution_rate (proportion of SIC-peer companies that
are dissolved), peer_total (total number of companies sharing the same SIC
code(s)).

High-scrutiny SIC codes:
  64205 — Activities of financial services holding companies
  70100 — Activities of head offices (non-financial holding companies)
  74990 — Non-trading company
  99999 — Dormant company

Risk level:
  is_holding AND dissolution_rate >= 0.40 → HIGH
  is_holding AND dissolution_rate < 0.40  → MEDIUM
  peer_total > 0 AND dissolution_rate >= 0.50 → MEDIUM
  otherwise → LOW

Compliance interpretation:
  Holding companies and dormant entities in the Companies House register are
  frequently used as intermediate layers in ownership chains. A holding company
  with a high peer dissolution rate indicates that similar entities in the same
  SIC group are being regularly struck off, which is consistent with
  disposable-vehicle typologies used in fraud and tax evasion schemes.

COMBINING SIGNALS
When synthesising the risk dimensions into a single narrative:

  - If any single dimension is HIGH: the overall assessment should note that
    the profile warrants escalation consideration, even if other dimensions
    are LOW. Explain which dimension drives the concern.

  - If two or more dimensions are MEDIUM and none is HIGH: flag for enhanced
    due diligence. Cumulative MEDIUM signals are materially more concerning
    than a single MEDIUM in isolation.

  - If all assessed dimensions are LOW: the profile is consistent with a
    standard trading company. Note any caveats (e.g. dimensions not assessed
    due to role restrictions or absent data).

  - Always name the overall risk level explicitly as the final word in the
    assessment (LOW / MEDIUM / HIGH).

────────────────────────────────────────────────────────────────────────────"""

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Tasks that are registered as MCP tools — passed to validate_plan.
# summarize_risk_for_company is a synthetic RiskAgent task (not an MCP tool).
_MCP_TOOLS: frozenset[str] = frozenset({
    "entity_lookup", "company_profile", "expand_ownership",
    "shared_address_check", "sic_context",
    "ownership_complexity_check", "control_signal_check",
    "address_risk_check", "industry_context_check",
    "retrieve_trace", "find_traces_by_entity",
})

# Maps agent task name → evaluate_stop_conditions signal key
_RISK_SIGNAL_MAP: dict[str, str] = {
    "ownership_complexity_check": "ownership_complexity",
    "control_signal_check":       "control_signals",
    "address_risk_check":         "address_risk",
    "industry_context_check":     "industry_context",
}


# ---------------------------------------------------------------------------
# Output models
# ---------------------------------------------------------------------------


@dataclass
class StepRecord:
    """Result record for one plan step.

    Attributes:
        step_id:        Stable identifier within the plan (e.g. "step_1").
        agent:          Agent that ran the step (e.g. "graph-agent").
        task:           Task name dispatched to the agent.
        success:        True when the agent completed without error.
        summary:        Short natural-language summary of what the step produced.
        findings:       Structured output keyed by task name.
        tools_executed: Ordered list of MCP tool names the agent called.
        error:          Error message when success is False and skipped is False.
        skipped:        True when the step was not executed (entity gate or halt).
        skip_reason:    Why the step was skipped, when skipped is True.
    """

    step_id: str
    agent: str
    task: str
    success: bool
    summary: str = ""
    findings: dict[str, Any] = field(default_factory=dict)
    tools_executed: list[str] = field(default_factory=list)
    error: str | None = None
    skipped: bool = False
    skip_reason: str | None = None

    @property
    def status(self) -> str:
        """Lifecycle status string for UI consumption.

        Derived from ``skipped`` and ``success`` so construction sites
        need not change.  "pending" and "running" are not emitted at
        runtime yet but are reserved for future async/streaming support.

        Returns one of: "success" | "failed" | "skipped".
        """
        if self.skipped:
            return "skipped"
        if self.success:
            return "success"
        return "failed"

    def to_dict(self) -> dict[str, Any]:
        return {
            "step_id":        self.step_id,
            "agent":          self.agent,
            "task":           self.task,
            "status":         self.status,
            "success":        self.success,
            "summary":        self.summary,
            "findings":       self.findings,
            "tools_executed": self.tools_executed,
            "error":          self.error,
            "skipped":        self.skipped,
            "skip_reason":    self.skip_reason,
        }


@dataclass
class OrchestratorResult:
    """
    Fully structured output from Orchestrator.run().

    Attributes:
        mode:               "investigate" or "trace".
        query:              Original user query string.
        trace_id:           Neo4j trace ID. Empty string if trace creation failed.
        success:            True when at least one step completed successfully.
        planner_output:     PlannerResult.to_dict() — mode, reason, entities, plan.
        resolved_entities:  {original_name: resolution_dict | None}.
                            None means the entity was not found in the graph.
        step_results:       Ordered StepRecord for every plan step (including skipped).
        final_answer:       Synthesised narrative drawn from step summaries.
        warnings:           Non-fatal issues (plan validation, stop-condition triggers).
        errors:             Issues that caused steps to be skipped or the planner to fail.
    """

    mode: str
    query: str
    trace_id: str
    success: bool
    planner_output: dict[str, Any]
    resolved_entities: dict[str, Any]
    step_results: list[StepRecord]
    final_answer: str
    warnings: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    retrieved_trace_id: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "mode":               self.mode,
            "query":              self.query,
            "trace_id":           self.trace_id,
            "success":            self.success,
            "planner_output":     self.planner_output,
            "resolved_entities":  self.resolved_entities,
            "step_results":       [sr.to_dict() for sr in self.step_results],
            "final_answer":       self.final_answer,
            "warnings":             self.warnings,
            "errors":               self.errors,
            "retrieved_trace_id":   self.retrieved_trace_id,
        }


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------


class Orchestrator:
    """
    Investigation workflow controller.

    Args:
        planner:       InvestigationPlanner for query → plan translation.
        mcp:           MCPToolClient used for validate_plan, resolve_entity,
                       and evaluate_stop_conditions.
        graph_agent:   GraphAgent instance.
        risk_agent:    RiskAgent instance.
        trace_agent:   TraceAgent instance.
        trace_service: TraceService for event logging and trace finalisation.
        trace_repo:    TraceRepository for initial trace persistence.
    """

    def __init__(
        self,
        planner: InvestigationPlanner,
        mcp: MCPToolClient,
        graph_agent: GraphAgent,
        risk_agent: RiskAgent,
        trace_agent: TraceAgent,
        trace_service: TraceService,
        trace_repo: TraceRepository,
        ai_client: AIClient | None = None,
    ) -> None:
        self._planner = planner
        self._mcp = mcp
        self._agents: dict[str, Any] = {
            "graph-agent":  graph_agent,
            "risk-agent":   risk_agent,
            "trace-agent":  trace_agent,
        }
        self._trace_service = trace_service
        self._trace_repo = trace_repo
        self._ai_client = ai_client

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def run(
        self,
        query: str,
        user_id: str = "system",
        on_progress: Any = None,
        confirmation_queue: "_queue_mod.Queue | None" = None,
        allowed_tools: "frozenset[str] | None" = None,
    ) -> OrchestratorResult:
        """
        Execute a full investigation from a natural-language query.

        Args:
            query:         Free-text investigation query.
            user_id:       Identifier for the requesting user, written to the trace.
            allowed_tools: Optional allowlist of MCP tool / task names the caller
                           is permitted to invoke.  When provided, any plan step
                           whose task name is NOT in this set is skipped with a
                           policy-denial skip_reason rather than being executed.
                           Infrastructure calls (validate_plan, resolve_entity,
                           evaluate_stop_conditions) are never filtered.
                           Pass ``None`` to disable enforcement (default).

        Returns:
            OrchestratorResult with planner output, resolved entities,
            per-step results, final answer, and the audit trace_id.
        """
        warnings: list[str] = []
        errors: list[str] = []

        # Short ID for log correlation across all events in this run.
        _run_id = str(uuid.uuid4())
        _short  = _run_id[:8]
        _log.info("[%s] Investigation started: %r", _short, query[:120])

        # ── 1. Plan ────────────────────────────────────────────────────
        try:
            plan = self._planner.plan(query, allowed_tools=allowed_tools)
        except Exception as exc:
            _log.error("[%s] Planner failed: %s", _short, exc)
            return OrchestratorResult(
                mode="investigate",
                query=query,
                trace_id="",
                success=False,
                planner_output={},
                resolved_entities={},
                step_results=[],
                final_answer="",
                warnings=warnings,
                errors=[f"Planner failed: {exc}"],
            )

        _log.info(
            "[%s] Routing: mode=%s entities=%s steps=%d",
            _short, plan.mode,
            [e.name for e in plan.entities],
            len(plan.plan),
        )
        if on_progress:
            on_progress("plan_ready", plan.to_dict())

        # ── 2. Create and persist trace ────────────────────────────────
        entity_name = plan.entities[0].name if plan.entities else query
        trace = InvestigationTrace(
            request_id=_run_id,
            entity_name=entity_name,
            question=query,
            user_id=user_id,
            mode=plan.mode,
        )
        self._trace_repo.save_trace(trace)
        if on_progress:
            on_progress("trace_created", {"trace_id": trace.request_id})

        self._trace_service.add_event(
            trace,
            TraceEvent(
                event_type=EventType.PLAN_CREATED,
                message=(
                    f"Plan: mode={plan.mode}, "
                    f"{len(plan.plan)} step(s), "
                    f"reason: {plan.reason}"
                ),
                payload=plan.to_dict(),
            ),
        )

        # ── 3. Validate plan via MCP ───────────────────────────────────
        mcp_steps = [
            {"step_id": s.step_id, "tool_name": s.task}
            for s in plan.plan
            if s.task in _MCP_TOOLS
        ]
        if mcp_steps:
            val = self._mcp.call_tool("validate_plan", {"steps": mcp_steps})
            if val.success and val.data:
                for ve in val.data.get("errors") or []:
                    msg = ve.get("message", str(ve)) if isinstance(ve, dict) else str(ve)
                    warnings.append(f"Plan validation: {msg}")
            elif not val.success:
                warnings.append(f"Plan validation unavailable: {val.error}")

        # ── 4. Resolve entities ────────────────────────────────────────
        resolved: dict[str, dict | None] = {}

        if plan.mode == "investigate":
            for entity in plan.entities:
                if entity.entity_type == "Trace":
                    # Trace IDs are self-referential — no graph resolution needed.
                    resolved[entity.name] = {
                        "canonical_name": entity.name,
                        "entity_type": "Trace",
                        "resolved": True,
                    }
                    continue

                res = self._mcp.call_tool("resolve_entity", {"name": entity.name})
                if res.success and (res.data or {}).get("canonical_name"):
                    all_matches = (res.data or {}).get("all_matches", [])
                    match_count = (res.data or {}).get("match_count", 1)

                    # Compute max score for later score_pct calculation
                    _raw_scores = [float(c.get("score") or 0) for c in all_matches]
                    _max_score  = max(_raw_scores) if _raw_scores else 1.0
                    # "Perfect" = candidate name is an exact match for the searched name
                    _perfect = [
                        c for c in all_matches
                        if (c.get("name") or "").lower().strip() == entity.name.lower().strip()
                    ]

                    confirmed: dict | None = None
                    _modal_shown = False

                    if len(_perfect) == 1:
                        # Single perfect match — auto-select without prompting
                        confirmed = _perfect[0]
                    elif confirmation_queue is not None and match_count > 1:
                        # Multiple candidates → show modal
                        # Only perfect matches if any; otherwise top 5 by score
                        modal_candidates = _perfect if _perfect else sorted(
                            all_matches,
                            key=lambda c: -round(
                                _difflib.SequenceMatcher(
                                    None, entity.name.lower(), (c.get("name") or "").lower()
                                ).ratio() * 100
                            ),
                        )[:5]
                        _modal_shown = True
                        if on_progress:
                            on_progress("entity_candidates", {
                                "name": entity.name,
                                "candidates": modal_candidates,
                                "match_count": len(modal_candidates),
                            })
                        try:
                            confirmed = confirmation_queue.get(timeout=300)
                        except _queue_mod.Empty:
                            confirmed = None

                    if _modal_shown and confirmed is None:
                        _log.info(
                            "[%s] Entity selection cancelled for '%s'",
                            _short, entity.name,
                        )
                        if on_progress:
                            on_progress("error", {"error": "Investigation cancelled."})
                        return OrchestratorResult(
                            mode=plan.mode,
                            query=query,
                            trace_id=trace.request_id,
                            success=False,
                            planner_output=plan.to_dict(),
                            resolved_entities={},
                            step_results=[],
                            final_answer="Investigation was cancelled during entity selection.",
                            warnings=warnings,
                            errors=["Investigation cancelled."],
                        )

                    if confirmed is not None:
                        # Use the auto-selected or user-confirmed candidate
                        confirmed_name = confirmed.get("name") or confirmed.get("canonical_name", entity.name)
                        _score_pct = round(
                            _difflib.SequenceMatcher(
                                None, entity.name.lower(), confirmed_name.lower()
                            ).ratio() * 100
                        )
                        resolved[entity.name] = {
                            "canonical_name":  confirmed_name,
                            "company_number":  confirmed.get("company_number"),
                            "status":          confirmed.get("status"),
                            "exact_match":     confirmed_name.lower() == entity.name.lower(),
                            "match_count":     match_count,
                            "match_score_pct": _score_pct,
                            "resolved":        True,
                        }
                    else:
                        _best_name = (res.data or {}).get("canonical_name", entity.name)
                        _score_pct = round(
                            _difflib.SequenceMatcher(
                                None, entity.name.lower(), _best_name.lower()
                            ).ratio() * 100
                        )
                        resolved[entity.name] = {**res.data, "resolved": True, "match_score_pct": _score_pct}

                    canonical   = resolved[entity.name]["canonical_name"]
                    company_no  = resolved[entity.name].get("company_number", "")
                    exact_match = resolved[entity.name].get("exact_match", True)
                    _log.info(
                        "[%s] Entity resolved: '%s' → '%s' (number=%s exact=%s)",
                        _short, entity.name, canonical, company_no, exact_match,
                    )
                    if on_progress:
                        on_progress("entity_resolved", {entity.name: resolved[entity.name]})
                    self._trace_service.add_event(
                        trace,
                        TraceEvent(
                            event_type=EventType.AGENT_REASONING,
                            message=f"Resolved '{entity.name}' → '{canonical}'",
                            payload={
                                **(res.data or {}),
                                "data_json": _json.dumps({
                                    "canonical_name":  resolved[entity.name].get("canonical_name"),
                                    "company_number":  resolved[entity.name].get("company_number"),
                                    "status":          resolved[entity.name].get("status"),
                                    "match_score_pct": resolved[entity.name].get("match_score_pct"),
                                }),
                            },
                        ),
                        entity_refs=[{"label": "Company", "name": canonical}],
                    )
                else:
                    _log.warning(
                        "[%s] Entity not resolved: '%s' — %s",
                        _short, entity.name, res.error,
                    )
                    resolved[entity.name] = None
                    if on_progress:
                        on_progress("entity_resolved", {entity.name: None})
                    msg = f"Entity '{entity.name}' could not be resolved in the graph."
                    errors.append(msg)
                    self._trace_service.add_event(
                        trace,
                        TraceEvent(
                            event_type=EventType.STEP_FAILED,
                            message=msg,
                            payload={"entity": entity.name, "resolve_error": res.error},
                        ),
                    )

        # ── 5. Execute plan steps ──────────────────────────────────────
        step_results: list[StepRecord] = []

        # If the primary entity could not be resolved, skip all steps immediately.
        if plan.mode == "investigate":
            primary = next(
                (e for e in plan.entities if e.entity_type not in ("Trace",)), None
            )
            if primary and resolved.get(primary.name) is None:
                for step in plan.plan:
                    step_results.append(StepRecord(
                        step_id=step.step_id,
                        agent=step.agent,
                        task=step.task,
                        success=False,
                        skipped=True,
                        skip_reason="Entity not resolved — all steps skipped.",
                    ))

        for step in plan.plan:
            # Skip steps already recorded above (entity not resolved).
            if any(r.step_id == step.step_id for r in step_results):
                continue

            # ── Role-policy gate ──────────────────────────────────────
            # Infrastructure tasks (validate_plan, resolve_entity,
            # evaluate_stop_conditions) are not plan steps so they are
            # never subject to this filter.  Only agent-dispatched tasks
            # are checked here.
            if allowed_tools is not None and step.task not in allowed_tools:
                skip_msg = (
                    f"Step '{step.task}' was not run: your role does not "
                    "permit this assessment."
                )
                _log.info(
                    "[%s] Step %s policy-denied: task=%s",
                    _short, step.step_id, step.task,
                )
                sr = StepRecord(
                    step_id=step.step_id,
                    agent=step.agent,
                    task=step.task,
                    success=False,
                    skipped=True,
                    skip_reason=skip_msg,
                )
                step_results.append(sr)
                if on_progress:
                    on_progress("step_complete", sr.to_dict())
                continue

            # ── Build context (inject canonical name if resolved) ──────
            context = _build_context(step, resolved)

            # ── Dispatch to agent ──────────────────────────────────────
            agent = self._agents.get(step.agent)
            if agent is None:
                msg = f"Unknown agent '{step.agent}' for step {step.step_id}."
                warnings.append(msg)
                step_results.append(StepRecord(
                    step_id=step.step_id,
                    agent=step.agent,
                    task=step.task,
                    success=False,
                    skipped=True,
                    skip_reason=msg,
                ))
                continue

            agent_label = _AGENT_DISPLAY.get(step.agent, step.agent)
            _log.info(
                "[%s] Step %s start: %s → %s",
                _short, step.step_id, agent_label, step.task,
            )
            if on_progress:
                on_progress("step_starting", {
                    "step_id": step.step_id,
                    "agent":   step.agent,
                    "task":    step.task,
                    "index":   len(step_results),
                    "n_total": len(plan.plan),
                })
            try:
                result: AgentResult = agent.run(step.task, context, trace)
            except Exception as exc:
                _log.error(
                    "[%s] Step %s error: %s → %s | %s",
                    _short, step.step_id, agent_label, step.task, exc,
                )
                result = AgentResult(
                    request_id=trace.request_id,
                    entity_name=entity_name,
                    success=False,
                    error=str(exc),
                )

            step_results.append(StepRecord(
                step_id=step.step_id,
                agent=step.agent,
                task=step.task,
                success=result.success,
                summary=result.summary,
                findings=result.findings,
                tools_executed=result.tools_used,
                error=result.error,
            ))
            if on_progress:
                on_progress("step_complete", step_results[-1].to_dict())

            _log.info(
                "[%s] Step %s complete: %s → %s | status=%s tools=%s",
                _short, step.step_id, agent_label, step.task,
                "success" if result.success else "failed",
                result.tools_used or [],
            )

            # ── Stop on failure ─────────────────────────────────────────
            if not result.success:
                remaining = plan.plan[plan.plan.index(step) + 1:]
                for rem in remaining:
                    step_results.append(StepRecord(
                        step_id=rem.step_id,
                        agent=rem.agent,
                        task=rem.task,
                        success=False,
                        skipped=True,
                        skip_reason=(
                            f"Halted — step '{step.step_id}' ({step.task}) failed."
                        ),
                    ))
                    if on_progress:
                        on_progress("step_complete", step_results[-1].to_dict())
                if remaining:
                    error_detail = f": {result.error}" if result.error else ""
                    warnings.append(
                        f"Execution halted after '{step.step_id}' ({step.task}) "
                        f"failed{error_detail}. {len(remaining)} step(s) skipped."
                    )
                break

            # ── Stop condition check ────────────────────────────────────
            if plan.stop_conditions and result.success:
                should_stop = self._check_stop_conditions(step_results, trace)
                if should_stop:
                    warnings.append(
                        f"Stop condition triggered after {step.step_id}. "
                        "Remaining steps skipped."
                    )
                    break

        # ── 6. Build final answer ──────────────────────────────────────
        final_answer = _build_final_answer(step_results, self._ai_client, entity_name)

        # If nothing succeeded, ask the AI to explain the failure.
        if self._ai_client and not any(sr.success for sr in step_results):
            user_prompt = (
                f"Query: {query}\n"
                f"Errors: {'; '.join(errors) if errors else 'none'}\n"
                f"Warnings: {'; '.join(warnings) if warnings else 'none'}"
            )
            try:
                ai_text = self._ai_client.generate_text(
                    system_prompt=_FAILURE_SYSTEM_PROMPT,
                    user_prompt=user_prompt,
                    max_tokens=120,
                )
                if ai_text:
                    final_answer = ai_text
            except Exception as exc:
                _log.warning("AI failure narrative unavailable: %s", exc)

        # ── 7. Finalize trace ──────────────────────────────────────────
        try:
            self._trace_service.finalize_trace(trace, final_answer)
        except Exception as exc:
            _log.error("Trace finalisation failed: %s", exc)
            warnings.append(f"Trace finalisation failed: {exc}")

        overall_success = any(sr.success for sr in step_results)
        n_done    = sum(1 for sr in step_results if sr.success)
        n_skipped = sum(1 for sr in step_results if sr.skipped)
        _log.info(
            "[%s] Investigation complete: success=%s mode=%s steps=%d/%d skipped=%d",
            _short, overall_success, plan.mode, n_done, len(step_results), n_skipped,
        )

        # Extract the target trace_id if a retrieve step succeeded.
        retrieved_trace_id = ""
        for sr in step_results:
            if not sr.success:
                continue
            if sr.task == "retrieve_trace":
                data = sr.findings.get("retrieve_trace") or {}
                retrieved_trace_id = data.get("trace_id", "")
            elif sr.task == "retrieve_and_summarize_trace":
                outer = sr.findings.get("retrieve_and_summarize_trace") or {}
                data = outer.get("trace_data") or {}
                retrieved_trace_id = data.get("trace_id", "")
            elif sr.task == "retrieve_latest_for_entity":
                outer = sr.findings.get("retrieve_latest_for_entity") or {}
                retrieved_trace_id = outer.get("latest_trace_id", "")
            if retrieved_trace_id:
                break

        return OrchestratorResult(
            mode=plan.mode,
            query=query,
            trace_id=trace.request_id,
            success=overall_success,
            planner_output=plan.to_dict(),
            resolved_entities=resolved,
            step_results=step_results,
            final_answer=final_answer,
            warnings=warnings,
            errors=errors,
            retrieved_trace_id=retrieved_trace_id,
        )

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _check_stop_conditions(
        self,
        step_results: list[StepRecord],
        trace: InvestigationTrace,
    ) -> bool:
        """
        Build a risk-signal findings dict from completed steps and call
        evaluate_stop_conditions. Returns True if the investigation should halt.

        Handles both direct risk tasks and the synthesised
        summarize_risk_for_company task (which bundles all four signals).
        """
        findings: dict[str, dict] = {}

        for sr in step_results:
            if not sr.success:
                continue

            # Direct risk task (e.g. ownership_complexity_check)
            if sr.task in _RISK_SIGNAL_MAP:
                signal_key = _RISK_SIGNAL_MAP[sr.task]
                task_data = sr.findings.get(sr.task) or {}
                if isinstance(task_data, dict) and "risk_level" in task_data:
                    findings[signal_key] = {"risk_level": task_data["risk_level"]}

        if not findings:
            return False

        res = self._mcp.call_tool("evaluate_stop_conditions", {"findings": findings})
        if not res.success or not res.data:
            return False

        should_stop: bool = bool(res.data.get("should_stop", False))
        if should_stop:
            self._trace_service.add_event(
                trace,
                TraceEvent(
                    event_type=EventType.INVESTIGATION_COMPLETE,
                    message=(
                        f"Stop condition met — overall_risk="
                        f"{res.data.get('overall_risk', 'UNKNOWN')}, "
                        f"escalate={res.data.get('escalate', False)}"
                    ),
                    payload=res.data,
                ),
            )
        return should_stop


# ---------------------------------------------------------------------------
# Module-level pure helpers
# ---------------------------------------------------------------------------


def _build_context(
    step: PlanStep,
    resolved: dict[str, dict | None],
) -> dict[str, Any]:
    """
    Build the context dict for an agent.run() call.

    Injects the canonical entity name from resolve_entity results when the
    step's company_name / name parameter matches a successfully resolved entity.
    """
    context = dict(step.parameters)
    for key in ("company_name", "name", "entity_name"):
        if key not in context:
            continue
        original = context[key]
        data = resolved.get(original)
        if data and data.get("canonical_name"):
            context[key] = data["canonical_name"]
    return context


def _build_final_answer(
    step_results: list[StepRecord],
    ai_client: AIClient | None = None,
    entity_name: str = "",
) -> str:
    """
    Synthesise a final answer from completed step summaries.

    Priority:
      1. trace-agent retrieve_and_summarize_trace / summarize_trace
      2. Individual risk task summaries — AI-synthesised with full narrative
         prompt if client available; plain join otherwise
      3. Last successful step summary
      4. Fallback message indicating what went wrong
    """
    successful = [sr for sr in step_results if sr.success and sr.summary]

    for sr in successful:
        if sr.task in ("retrieve_and_summarize_trace", "summarize_trace"):
            return sr.summary

    _INDIVIDUAL_RISK_TASKS = frozenset({
        "address_risk_check",
        "control_signal_check",
        "ownership_complexity_check",
        "industry_context_check",
    })
    risk_summaries = [
        sr.summary
        for sr in successful
        if sr.task in _INDIVIDUAL_RISK_TASKS
    ]

    _POLICY_MARKER = "role does not permit"
    policy_skipped_tasks = [
        sr.task for sr in step_results
        if sr.skipped
        and _POLICY_MARKER in (sr.skip_reason or "")
        and sr.task in _INDIVIDUAL_RISK_TASKS
    ]

    if risk_summaries:
        if ai_client:
            try:
                prefix = f"Company: {entity_name}\n\n" if entity_name else ""
                user_prompt = prefix + "\n".join(f"- {s}" for s in risk_summaries)
                if policy_skipped_tasks:
                    skipped_labels = ", ".join(
                        t.replace("_check", "").replace("_", " ")
                        for t in policy_skipped_tasks
                    )
                    user_prompt += (
                        f"\n\n[Note: the following dimensions were not assessed due to "
                        f"role restrictions: {skipped_labels}]"
                    )
                synthesized = ai_client.generate_text(
                    system_prompt=_RISK_NARRATIVE_PROMPT,
                    user_prompt=user_prompt,
                    max_tokens=200,
                )
                if synthesized:
                    return synthesized
                _log.warning("_build_final_answer: AI synthesis returned empty string")
            except Exception as exc:
                _log.warning("_build_final_answer: AI synthesis failed (%s), using raw join", exc)
        return " ".join(risk_summaries)

    if policy_skipped_tasks:
        denied_labels = [
            t.replace("_check", "").replace("_", " ") for t in policy_skipped_tasks
        ]
        plural = len(denied_labels) > 1
        joined = ", ".join(denied_labels)
        return (
            f"The requested {'assessments' if plural else 'assessment'} "
            f"({joined}) {'are' if plural else 'is'} not available for your role. "
            "Contact a Senior Risk Analyst for a full assessment."
        )

    if successful:
        return successful[-1].summary

    # Nothing succeeded — explain why
    skipped = [sr for sr in step_results if sr.skipped]
    if skipped:
        return (
            "Investigation could not complete: the requested entity was not found "
            "in the graph. Verify the company name and try again."
        )

    errs = [sr.error for sr in step_results if sr.error]
    if errs:
        return f"Investigation failed: {errs[0]}"

    return "No results were obtained for this query."
